name: Generate Workshop HTML from Markdown

on: [push]

jobs:
  generate-html:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Workshops Repo
      uses: actions/checkout@v2
      with:
        path: workshops
    - name: Checkout HTML generator
      uses: actions/checkout@v2
      with:
        repository: simonwiles/workshop-html-generator
        path: html-generator
    - name: Install dependencies
      run: |
        cd html-generator
        python3 -m pip install --upgrade pip
        pip3 install setuptools
        pip3 install -r requirements.txt
    - name: Generate HTML
      run: |
        cd workshops
        for i in $(find ./ -iname '*.md' ! -iname 'README.md'); do
          echo "Generating $i"; 
          python3 ../html-generator/gen_html.py -t ../html-generator/template.html "$i" > "${i%%.md}.html";
          git add "$i";
        done;
    - name: Commit HTML
      run: |
        cd workshops
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "Automated report"
        git push
