name: Generate Workshop HTML from Markdown

on: [push]

jobs:
          
  generate-html:
    runs-on: ubuntu-latest
    steps:
    - name: Pre-Check
      run: |
        export MDFILES=$(
          curl --silent https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} | 
          jq --raw-output '.files[].filename | match(".*(?<!README)\\.md").string');
        echo "$MDFILES"
    - name: Checkout Workshops Repo
      if: env.MDFILES
      uses: actions/checkout@v2
      with:
        path: workshops
    - name: Checkout HTML generator
      if: env.MDFILES
      uses: actions/checkout@v2
      with:
        repository: simonwiles/workshop-html-generator
        path: html-generator
    - name: Install dependencies
      if: env.MDFILES
      run: |
        cd html-generator
        python3 -m pip install --upgrade pip
        pip3 install setuptools
        pip3 install -r requirements.txt
    - name: Generate HTML
      if: env.MDFILES
      run: |
        cd workshops
        for i in $MDFILES;
        do
          echo "Generating ${i%%.md}.html"; 
          python3 ../html-generator/gen_html.py -t ../html-generator/template.html "$i" > "${i%%.md}.html";
          git add "${i%%.md}.html";
        done;
    - name: Commit HTML
      if: env.MDFILES
      run: |
        cd workshops
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -am "Auto-generated HTML"
        git push
