name: Generate Workshop HTML from Markdown

on: [push]

jobs:
  generate-html:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Workshops Repo
      uses: actions/checkout@v2
      with:
        path: workshops
    - name: Checkout HTML generator
      uses: actions/checkout@v2
      with:
        repository: simonwiles/workshop-html-generator
        path: html-generator
    - name: Install dependencies
      run: |
        cd html-generator
        python3 -m pip install --upgrade pip
        pip3 install setuptools
        pip3 install -r requirements.txt
    - name: Generate HTML
      run: |
        ls -alh
        cd workshops
        ls -alh
        for i in $(find ./ -iname '*.md'); do python3 ../html-generator/gen_html.py -t ../html-generator/template.html "$i" > "${i%%.md}.html"; done;
        ls -alh
