name: Generate Workshop HTML from Markdown

on: [push]

jobs:

  generate-html:
    runs-on: ubuntu-latest
    steps:
    - name: Pre-Check
      run: |
        MDFILES=$(
          curl --silent https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} |
          jq --raw-output --compact-output '.files[] | select(.filename | match(".*(?<!README)\\.md")) | {filename, status}');
        echo "::set-env name=MDFILES::'$MDFILES'";
    - name: Checkout Workshops Repo
      if: env.MDFILES
      uses: actions/checkout@v2
      with:
        path: workshops
    - name: Checkout HTML generator
      if: env.MDFILES
      uses: actions/checkout@v2
      with:
        repository: simonwiles/workshop-html-generator
        path: html-generator
    - name: Install dependencies
      if: env.MDFILES
      run: |
        cd html-generator
        python3 -m pip install --upgrade pip
        pip3 install setuptools
        pip3 install -r requirements.txt
    - name: Remove HTML for deleted markdown files
      if: env.MDFILES
      run: |
        for i in $(echo $MDFILES | jq --raw-output 'select(.status == "removed").filename');
        do
          HTML_FILE="${i%%.md}.html"
          if [ -e "$HTML_FILE" ];
          then
            echo "Removing $HTML_FILE";
            git rm "$HTML_FILE";
          fi;
        done;
    - name: Generate HTML
      if: env.MDFILES
      run: |
        cd workshops
        for i in $(echo $MDFILES | jq --raw-output 'select(.status != "removed").filename');
        do
          HTML_FILE="${i%%.md}.html"
          echo "Generating $HTML_FILE";
          python3 ../html-generator/gen_html.py -t ../html-generator/template.html "$i" > "$HTML_FILE";
          git add "$HTML_FILE";
        done;
    - name: Commit HTML
      if: env.MDFILES
      run: |
        cd workshops
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git commit -am "Auto-generated HTML"
        git push